[package]
name = "rocket_oidc"
version = "0.1.0"
edition = "2024"

[dependencies]
jsonwebtoken = "9.3.1"
openidconnect = "4.0.0"
rocket = "0.5.1"
serde = "1.0.219"
serde_derive = "1.0.219"
serde_json = "1.0.140"
